version: '3.8'

volumes:
  pocketbase_data:

services:
  pocketbase:
    image: ghcr.io/bennetrr/tgym-escape-room-pocketbase:v1.2.2
    container_name: tgym-escape-room-pocketBase
    restart: always
    ports:
      - "3456:8080"
    volumes:
      - type: volume
        source: pocketbase_data
        target: /pb/

  app:
    image: ghcr.io/bennetrr/tgym-escape-room-app:v1.2.2
    container_name: tgym-escape-room-app
    restart: always
    ports:
      - "3457:80"
