name: Build Docker Images

on:
  release:
    types:
      - created
  workflow_dispatch:

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build PocketBase Image
        uses: docker/build-push-action@v3
        with:
          file: ./pocketbase.Dockerfile
          context: .
          tags: ghcr.io/bennetrr/tgym-escape-room-pocketbase:${{ github.event.release.tag_name }}
          push: true
          labels:
            - "org.opencontainers.image.version": ${{ github.event.release.tag_name }}

      - name: Build App Image
        uses: docker/build-push-action@v3
        with:
          file: ./app.Dockerfile
          context: .
          tags: ghcr.io/bennetrr/tgym-escape-room-app:${{ github.event.release.tag_name }}
          push: true
          labels:
            - org.opencontainers.image.version=${{ github.event.release.tag_name }}

      - name: Update latest tag on PocketBase Image
        uses: silverlyra/latest-image-action@main
        with:
          repository: ghcr.io/bennetrr/tgym-escape-room-pocketbase
          candidate-tag: ${{ github.event.release.tag_name }}

      - name: Update latest tag on App Image
        uses: silverlyra/latest-image-action@main
        with:
          repository: ghcr.io/bennetrr/tgym-escape-room-app
          candidate-tag: ${{ github.event.release.tag_name }}
