name: Code Style Check

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Dependencies
        working-directory: src
        run: |
          yarn install --dev
          yarn add @microsoft/eslint-formatter-sarif@2.1.7
      - name: Run ESLint
        working-directory: src
        run: yarn eslint
          --config .eslintrc.json
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: src/eslint-results.sarif
          wait-for-processing: true
