name: Code Style Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  svelte-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          yarn install --dev

      - uses: prgm-dev/svelte-check-pr-annotator@main

      - name: Run svelte-check
        run: yarn run check --output machine --use-new-transformation true
